# Generated by Django 4.1.2 on 2022-11-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=200)),
                ('email', models.CharField(editable=False, max_length=200)),
                ('phone', models.CharField(editable=False, max_length=11)),
                ('message', models.TextField(editable=False, max_length=500)),
            ],
        ),
    ]
