# Generated by Django 4.1.2 on 2022-11-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_alter_mail_email_alter_mail_message_alter_mail_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='email',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='mail',
            name='message',
            field=models.TextField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='mail',
            name='name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='mail',
            name='phone',
            field=models.CharField(editable=False, max_length=11),
        ),
    ]
