# Generated by Django 4.1.2 on 2022-11-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_alter_mail_email_alter_mail_message_alter_mail_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'managed': False},
        ),
    ]
