# Generated by Django 4.1.2 on 2022-11-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_alter_mail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={},
        ),
    ]
