# Generated by Django 4.1.2 on 2022-10-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_email_alter_contract_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='name_contract',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='photo_contract',
            new_name='photo',
        ),
    ]
