# Generated by Django 4.1.2 on 2022-10-31 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_rename_name_contract_contract_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cep_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_born',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contract',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
