# Generated by Django 4.1.2 on 2022-10-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_cep_number_contract_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='cep_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
